language: python
sudo: false
python:
  - 3.6

env:
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0


install:
  - pip install tox codecov

script:
  - tox -e "d${DJANGO//.}-py${TRAVIS_PYTHON_VERSION//.}"

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
